name: Issue Certificate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: ssets/kubectl@v1  # Make sure this action exists and is compatible
      with:
        version: 'latest'  # Specify the exact version if necessary

    - name: Issue Certificate
      run: |
        kubectl apply -f .github/workflows/certificate-issuer.yaml
