name: Issue Certificate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup kubectl
      uses: azure/setup-kubectl@v2
      with:
        version: 'latest'

    - name: Issue Certificate
      run: |
        kubectl apply -f .github/workflows/certificate-issuer.yaml
