name: Issue Certificate

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
  schedule:
    - cron: '0 0 * * *'  # Trigger daily at midnight (UTC)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1  # Ensure this action is correct and exists
      with:
        version: 'v1.24.0'

    - name: Issue Certificate
      run: |
        kubectl apply -f .github/workflows/certificate-issuer.yaml
